openapi: 3.1.0
info:
  title: CS API
  description: Library of Coffee - Customer Service API
  contact:
    name: Library of Coffee
  version: 1.0.0
servers:
- url: /
  description: Current Server
tags:
- name: Sample
  description: サンプルAPI
paths:
  /api/samples/{id}:
    get:
      tags:
      - Sample
      summary: サンプル取得
      description: 指定されたIDのサンプルを取得します
      operationId: getSampleById
      parameters:
      - name: id
        in: path
        description: サンプルID
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: 取得成功
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/SampleResponse"
              examples:
                success:
                  summary: 取得成功例
                  description: success
                  value:
                    id: 1
                    name: コーヒー豆A
        "404":
          description: サンプルが見つかりません
components:
  schemas:
    SampleResponse:
      type: object
      description: サンプルレスポンス
      properties:
        id:
          type: integer
          format: int64
          description: サンプルID
          example: 1
        name:
          type: string
          description: サンプル名
          example: コーヒー豆A
